{% set version = '2.2.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-captioner
  version: {{ version|replace("-", "_") }}

source:
  fn: captioner_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/captioner_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/captioner/captioner_{{ version }}.tar.gz
  sha256: 72f92d757a47bae883cc95eb60a115c141aaf5eddcc15bc8068ea0faea15e775

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('captioner')"           # [not win]
    - "\"%R%\" -e \"library('captioner')\""  # [win]

about:
  home: https://github.com/adletaw/captioner
  license: MIT
  summary: Provides a method for automatically numbering figures, tables, or other objects.  Captions
    can be displayed in full, or as citations. This is especially useful for adding
    figures and tables to R markdown documents without having to numbering them manually.
  license_family: MIT

extra:
  recipe-maintainers:
    - tfenne
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
