travis:
  secure:
    BINSTAR_TOKEN: A0ZqHs+YDJaX00E4o2gtnFfp+Nxn9U9HHEi7NU2vSwYC+PNI0H9XSGWM06qeBD8MB1YF10Y0NgRqJrCsaP+RVCBuRHt3XuXMGhgdYkxtbCBCzgEIwfcRSogcJ6uepXdrB+gV68K3VoNB18FbKu+5/xB6HIqKvJez/X1AAZFP9+tPxz9bIGn5T00YsgFriqtC3ZMSm+3BpWnydqo+pD6JdSa2XCaTdSFUL5HjDPfMMvOo9BRThcbYSsvb+yZ36vB1CzaLVEvAJaNtcuktcvUdtpBBAcFWPPrvhUpa6/v26F3ESYrGsWCuInHMkqVE86LLBvp5YTabEloUrqtV75D5gKmh+oY5UJTS0oLtqK4y/4bTDuSQNC3K54WdlH+KtcwpS0TzdFQPWZ2sIAis/o0hp0vVlPVFhuxKAxdaZSxayloIOXwVKXXsIytJmNKDvPurcfD2YbN3IOZo4O/cmlnLCODVWzF+f8PkobOBLlMtlMppOax39DHtM2h8maQnusOmEiKumJZp5TbMwNXnldVChdmwRgaOMmancQmISGKgZCwOv7/O9LlADEaZMMh4SWIkY9XuVNxRPLbXnVBZ38HOMQvQAO+srmEhZ9lKHZUMRKT5FChf0jk+v+JhCOt6dqQ3Zllbs1F6saBwHpCdgLwDiTggvmL9ggLNQMXj2BwUS8I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
